step1_moving_points:
  input_dir:       "local_file/raw_file"
  output_dir:      "local_file/step1_file"
  file_name:       "ALL"                      # “ALL” 或者指定单个待处理文件
  faststart:       true                       # MP4 faststart 标志
  reencode:        true                       # 是否使用 H.264 重编码输出
  max_points:      20                         # 每帧最多标注运动目标数
  min_area:        20                         # 忽略面积小于此值的轮廓（噪声过滤）
  max_area_ratio:  0.01                       # 忽略面积占帧面积比例超过此阈值（过滤云层等大块）
  speed_thresh:    20                         # 灰度差分阈值，仅保留运动速度大于此值的像素

step2_trace: # IMU X Y反向了，需要step3额外处理！！！！！！！！！ 
  input_video_dir:  "local_file/raw_file"
  input_csv_dir:    "local_file/step1_file"
  output_dir:       "local_file/step2_file"
  file_name:        "Camera_20250719_104640.mp4"                     # “ALL” 或者指定单个待处理文件
  start_frame:      60                         # 0 = 从头
  end_frame:        1800                         # 0 = 到末尾
  init_radius:      80                        # 初始搜索半径 (px)
  ref_x:            760                       # 目标初始位置， 0 = 最大运动目标
  ref_y:            140                       # 目标初始位置， 0 = 最大运动目标
  radius_growth:    1                         # 每丢 1 帧半径增量
  target_fps:       10                        # fps > 0 且 < 源 fps 时生效
  faststart:        true
  reencode:         false

step3_observed_angle:
  raw_csv_dir:      "local_file/raw_file"
  input_video_dir:  "local_file/step2_file"
  input_csv_dir:    "local_file/step2_file"
  output_dir:       "local_file/step3_file"
  file_name:        "Camera_20250719_104640.mp4"                     # “ALL” 或者指定单个待处理文件
  arrow_scale:      100                       # 箭头像素长度
  min_track_area:   400                       # 小于此像素面积的 track 不写入 JPG/TXT
  max_track_area:   999999                    # 大于此面积的 track 不写入 JPG/TXT

  faststart:        true                      # 输出 mp4 添加 fast-start
  field_map:                                  # csv中对应的列标签名
    px:        track_x
    py:        track_y
    roll:      angle_y
    pitch:     angle_x
    yaw:       tilt
    cam_pitch: g1
  fov_h:           125.0                      # 相机水平视场角
  fov_v:           69.0                       # 相机垂直视场角

step4_yolo_train:
  dataset_dir: "local_file/step3_file/dataset"
  model:       "local_file/step4_file/models/yolo11l-obb.yaml"
  epochs:      2000
  imgsz:       640
  batch:       16
  freeze:      20
  project:     "local_file/step4_file"
  name:        "drone_finetune"
  resume":      false

 
